name: stock_quotes
description: A stock quotes display application

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.0
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  youtube_player_flutter: ^8.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/set-logo.svg
